In [19]:
import os
import pandas as pd
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import os.path, time
from filecmp import dircmp
a="U:\stage\BAL_Lyon"
b="U:\stage1"
diff = dircmp(a, b)
ta=[]
for ldif_file in diff.left_only:
    print(os.path.join(a, ldif_file))
    fhand = open(os.path.join(a, ldif_file),'r',encoding='utf8')
    contenu = fhand.read()
    soup = BeautifulSoup(contenu, "html.parser")
    message = soup.get_text(separator=' ')
    date_crea = time.ctime(os.path.getctime(os.path.join(a, ldif_file)))
    date_modif = time.ctime(os.path.getmtime(os.path.join(a, ldif_file)))
    d = {'Messages': message,'Nom du fichier':ldif_file, 'Date de création':date_crea, 'Date de modification':date_modif,
        'catégorie':''}
    ta.append(d)

U:\stage\BAL_Lyon\Nouveau document texte (10).txt
U:\stage\BAL_Lyon\Nouveau document texte (11).txt

In [20]:
t= pd.DataFrame(ta,index=None)
t

,Messages,Nom du fichier,Date de création,Date de modification,catégorie
0,,Nouveau document texte (10).txt,Fri Jun 4 20:33:47 2021,Fri Jun 4 20:33:47 2021,
1,,Nouveau document texte (11).txt,Fri Jun 4 20:37:54 2021,Fri Jun 4 20:37:54 2021,

In [21]:
df=pd.read_excel('final_210416.xlsx',index_col=False)
df

,Messages,Nom du fichier,Date de création,Date de modification,catégorie
0,NaN,Nouveau document texte (5).txt,Fri Jun 4 16:32:08 2021,Fri Jun 4 16:32:08 2021,NaN
1,NaN,Nouveau document texte (5).txt,Fri Jun 4 16:32:08 2021,Fri Jun 4 16:32:08 2021,NaN
2,NaN,Nouveau document texte (5).txt,Fri Jun 4 16:32:08 2021,Fri Jun 4 16:32:08 2021,NaN
3,NaN,Nouveau document texte (5).txt,Fri Jun 4 16:32:08 2021,Fri Jun 4 16:32:08 2021,NaN
4,NaN,Nouveau document texte (6).txt,Fri Jun 4 19:39:05 2021,Fri Jun 4 19:39:05 2021,NaN
5,NaN,Nouveau document texte (7).txt,Fri Jun 4 19:39:09 2021,Fri Jun 4 19:39:09 2021,NaN
6,NaN,Nouveau document texte (8).txt,Fri Jun 4 19:57:09 2021,Fri Jun 4 19:57:09 2021,NaN
7,NaN,Nouveau document texte (10).txt,Fri Jun 4 20:33:47 2021,Fri Jun 4 20:33:47 2021,NaN
8,NaN,Nouveau document texte (10).txt,Fri Jun 4 20:33:47 2021,Fri Jun 4 20:33:47 2021,NaN

In [22]:
global_dataset = pd.concat([df,t ], ignore_index=True)

In [24]:
global_dataset.to_excel("final_210416.xlsx",index=False)